apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80         # Port accessible depuis l'intérieur du cluster
      targetPort: 3000 # Port de l'application dans le conteneur
      nodePort: 30007  # Port accessible depuis l'extérieur (doit être entre 30000-32767)
  type: NodePort  # On remplace LoadBalancer par NodePort
