apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  namespace: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      serviceAccountName: blog-app-sa 
      initContainers:
      - name: vault-agent-init
        image: vault:latest
        command:
        - "/bin/sh"
        - "-c"
        - |
          vault kv get -field=username secret/mysql > /vault/secrets/db_user
          vault kv get -field=password secret/mysql > /vault/secrets/db_password
        volumeMounts:
        - name: vault-secrets
          mountPath: "/vault/secrets"
      containers:
      - name: blog
        image: bouzidieslem/nodejs_app_web:v5
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-secrets
              key: db_password
        - name: DB_NAME
          value: "blog_db"
        volumeMounts:
        - name: vault-secrets
          mountPath: "/vault/secrets"
      volumes:
      - name: vault-secrets
        emptyDir: {}
