apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqll-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # La taille que tu demandes pour le PVC
  storageClassName: standard

