apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqll-pv
spec:
  capacity:
    storage: 1Gi  # Taille du volume
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data"  # Emplacement local dans ta machine hôte, ou tu peux utiliser d'autres types comme NFS, GCEPersistentDisk, etc.
